# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.raccoltaDati.RilevDatiPrdTS', 'it.softre.thip.produzione.raccoltaDati.YRilevDatiPrdTS', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.raccoltaDati.web.RilevDatiPrdTSFormActionAdapter', 'it.softre.thip.produzione.raccoltaDati.web.YRilevDatiPrdTSFormActionAdapter', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.raccoltaDati.web.RilevDatiPrdTSWebFormModifier', 'it.softre.thip.produzione.raccoltaDati.web.YRilevDatiPrdTSWebFormModifier', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/NuovaDichiarazione.js', 'it/softre/thip/produzione/raccoltaDati/YNuovaDichiarazione.js', '2', 'N');
